termo =int(input("Quantos termos quer mostrar ?"))
t1= 0
t2= 1
f=0
print("{} -> {}".format(t1, t2), end="")
while f <= termo:
    t3 = t1 + t2
    print(" {}-> ".format(t3),end="")
    t1 = t2
    t2= t3
    f+=1